version: '3.8'

services:
  nginx-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs:rw
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped
    networks:
      - nginx-deploy-test1_proxy-network
      
  letsencrypt-companion:
    image: nginxproxy/acme-companion
    container_name: letsencrypt-companion
    volumes_from:
      - nginx-proxy
    volumes:

      - ./acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DEFAULT_EMAIL=kevenis13@gmail.com
      - NGINX_PROXY_CONTAINER=nginx-proxy

    restart: unless-stopped
    depends_on:
      - nginx-proxy
    networks:
      - nginx-deploy-test1_proxy-network

networks:
  nginx-deploy-test1_proxy-network:
    external: true